### PR TITLE
Compile with kernel v5.15

### PR DESCRIPTION
**Pull request by isqad**
```
$ sudo uname -a
Linux andypc 5.16.0-arch1-1 #1 SMP PREEMPT Mon, 10 Jan 2022 20:11:47 +0000 x86_64 GNU/Linux

$ make
<...>
/work/projects/rtl8188eus/core/rtw_br_ext.c:20:18: fatal error: net/ipx.h: No such file or directory
   20 |         #include <net/ipx.h>
      |                  ^~~~~~~~~~~
compilation terminated.
make[2]: *** [scripts/Makefile.build:287: /work/projects/rtl8188eus/core/rtw_br_ext.o] Error 1
make[1]: *** [Makefile:1846: /work/projects/rtl8188eus] Error 2
make[1]: Leaving directory '/usr/lib/modules/5.16.0-arch1-1/build'
make: *** [Makefile:2062: modules] Error 2
```

The ipx network layer has been [removed](https://lore.kernel.org/netdev/1710508.VLH7GnMWUR@x2/T/) from kernel v5.15.

### CODE REVIEW

**Comment by AyushPithale** [comment]
did you got solution

**Comment by narcomerk19** [comment]
> _No description provided._

Bro, did you fix those error upon make command? it happens on kali linux kernel 5.15.0, will this be the solution ?

**Comment by isqad** [comment]
> Bro, did you fix those error upon make command? it happens on kali linux kernel 5.15.0, will this be the solution ?

Hi!
Sure, I fixed and build the driver by `make`

 I'm using Arch Linux with kernel 5.15
The issue related to kernel versions  >=5.15

**Comment by narcomerk19** [comment]
> > Bro, did you fix those error upon make command? it happens on kali linux kernel 5.15.0, will this be the solution ?
> 
> Hi!
> Sure, I fixed and build the driver by `make`
> 
>  I'm using Arch Linux with kernel 5.15
> The issue related to kernel versions  >=5.15

I compile the file using your added comment.. it seems to work fine for me, the only thing which is buggy is the check kill command.

**Comment by amnh30** [comment]
pls upgrade th driver to support kernel 5.15

**Comment by chShiraz** [comment]
> _No description provided._

can you please share steps for it?

**Comment by isqad** [comment]
> can you please share steps for it?

Done

**Comment by isqad** [comment]
merge?
